// Tiny dependency-free CLI flag parser for create-iai.
//
// Supported grammar: `create-iai [name] [options]`. Boolean flags may be
// negated with `--no-<flag>`. Value flags accept `--flag value` and
// `--flag=value`. Unknown flags abort with a helpful message instead of being
// silently ignored.

const VALUE_FLAGS = new Map([
  ['--name', 'name'],
  ['--dir', 'dir'],
  ['--template-ref', 'templateRef'], // template branch/tag (on the gated download)
  ['--template-id', 'templateId'], // id from the TEMPLATES catalog (live1 | live2 | …)
  ['--update-deps', 'updateDeps'], // none | safe
  ['--shadcn-preset', 'shadcnPreset'],
  ['--shadcn-block', 'shadcnBlock'], // "sidebar-07", "dashboard-01,login-01" or "none"
  ['--repo', 'repo'],
  ['--port', 'port'], // server port for --ui mode (default: 4599)
  ['--mode', 'mode'], // harness | full  (harness = harness only; full = harness + template)
  // Stack: recomendada (template) | depois (everything pending, decide in Pi) |
  // category=option pairs (e.g. backend=hono,db=neon,orm=drizzle) — semantic
  // validation in src/lib/stack.js (parseStackFlag).
  ['--stack', 'stack'],
  ['--agent-files', 'agentFiles'], // add | replace — target already has agent files (.claude, CLAUDE.md…), any mode
  // Addons ("maximal" template → the CLI removes whatever isn't chosen):
  ['--preset', 'preset'], // minimo | padrao | saas (completo = deprecated alias of saas)
  ['--addons', 'addons'], // "commitlint,knip,…" | none | all
  ['--observability', 'observability'], // "sentry,logging" | none
  ['--analytics', 'analytics'], // none | posthog | vercel-analytics
  ['--security', 'security'], // "csp,rate-limit" | none
  ['--emails', 'emails'], // none | resend
  ['--platform', 'platform'], // "notifications,…" | none (Platform group; templates may extend it via manifest)
  ['--payments', 'payments'], // none | stripe | clerk-billing | asaas
  ['--storage', 'storage'], // convex | r2
  ['--keys', 'keys'], // .env file with service keys (generated by the --ui web UI)
  ['--tenancy', 'tenancy'], // single (Live 1) | multi (Live 2, multi-tenant)
  ['--api', 'api'], // override for the community API base (dev/testing)
]);

const BOOL_FLAGS = new Map([
  ['--ui', 'ui'],
  ['--terminal', 'terminal'], // forces the terminal assistant (kept for compatibility)
  ['--web', 'ui'],
  ['--yes', 'yes'],
  ['-y', 'yes'],
  ['--push', 'push'],
  ['--deploy', 'deploy'],
  ['--harness', 'harness'],
  ['--harness-only', 'harnessOnly'], // shortcut for --mode harness
  ['--public', 'public'],
  ['--private', 'private'],
  ['--skip-shadcn', 'skipShadcn'],
  ['--skip-webhook', 'skipWebhook'],
  ['--skip-storage', 'skipStorage'],
  ['--skip-github', 'skipGithub'],
  ['--skip-deploy', 'skipDeploy'],
  ['--skip-harness', 'skipHarness'],
  ['--fia', 'fia'],
  ['--skip-fia', 'skipFia'],
  ['--impeccable', 'impeccable'],
  ['--skip-impeccable', 'skipImpeccable'],
  ['--help', 'help'],
  ['-h', 'help'],
  ['--version', 'version'],
  ['-v', 'version'],
  ['--login', 'login'], // authenticates (device flow) and exits
  ['--logout', 'logout'], // removes/revokes the CLI token and exits
  ['--whoami', 'whoami'], // shows subscription status and exits
  ['--verify', 'verify'], // audits an ALREADY-installed project and exits
  ['--update-runtime', 'updateRuntime'], // re-stamps the FIA/Pi runtime of an installed project and exits
  ['--force', 'force'], // --update-runtime: overwrite locally modified runtime files too (with backup)
  ['--json', 'json'], // --verify / --update-runtime: machine-readable JSON report on stdout
]);

const NEGATABLE = new Map([
  ['--no-ui', 'ui'],
  ['--no-push', 'push'],
  ['--no-deploy', 'deploy'],
  ['--no-harness', 'harness'],
  ['--no-fia', 'fia'],
  ['--no-impeccable', 'impeccable'],
  ['--no-update-deps', 'noUpdateDeps'],
]);

/**
 * Parse process argv (already sliced past node + script).
 * `warnings` are non-fatal notices (deprecated aliases etc.) the entry point
 * prints without aborting.
 * @returns {{flags: object, errors: string[], warnings: string[]}}
 */
export function parseArgs(argv) {
  const flags = {};
  const errors = [];
  const warnings = [];
  const positionals = [];

  for (let i = 0; i < argv.length; i++) {
    const raw = argv[i];
    const [token, inlineValue] = splitInline(raw);

    if (NEGATABLE.has(token)) {
      const key = NEGATABLE.get(token);
      if (key === 'noUpdateDeps') flags.noUpdateDeps = true;
      else flags[key] = false;
      continue;
    }
    if (BOOL_FLAGS.has(token)) {
      flags[BOOL_FLAGS.get(token)] = true;
      continue;
    }
    if (VALUE_FLAGS.has(token)) {
      // Inline (`--flag=value`) vs next-token (`--flag value`) form. Only
      // advance past argv[i + 1] AFTER it is accepted as the value — the old
      // unconditional rewind reprocessed the same token forever when the
      // inline value itself looked like a flag (e.g. `--name=--test`).
      const fromNext = inlineValue == null;
      const value = fromNext ? argv[i + 1] : inlineValue;
      if (value == null || value === '' || value.startsWith('-')) {
        // An inline value that LOOKS like a flag (`--name=--test`) is rejected
        // too, but with an honest message: a value WAS given — it just reads
        // like another flag, which is almost always a typo.
        if (!fromNext && value) {
          errors.push(
            `The ${token} flag needs a value, but "${value}" starts with "-" — that looks like a flag, not a value.`,
          );
        } else {
          errors.push(`The ${token} flag needs a value. E.g.: ${token} <value>`);
        }
        continue; // don't swallow the next flag
      }
      if (fromNext) i++;
      flags[VALUE_FLAGS.get(token)] = value;
      continue;
    }
    if (token.startsWith('-')) {
      errors.push(`Unknown flag: ${token} (see --help)`);
      continue;
    }
    positionals.push(token);
  }

  if (positionals.length > 0 && !flags.name) flags.name = positionals[0];
  if (positionals.length > 1) errors.push(`Extra arguments ignored: ${positionals.slice(1).join(' ')}`);

  if (flags.public && flags.private) errors.push('Use --public OR --private, not both.');
  if (flags.updateDeps && !['none', 'safe'].includes(flags.updateDeps)) {
    errors.push('--update-deps accepts: none | safe');
  }
  if (flags.noUpdateDeps) {
    flags.updateDeps = 'none';
    delete flags.noUpdateDeps;
  }

  // `--harness-only` is sugar for `--mode harness`.
  if (flags.harnessOnly) {
    if (flags.mode && flags.mode !== 'harness') {
      errors.push('--harness-only conflicts with --mode ' + flags.mode + ' (use one or the other).');
    }
    flags.mode = 'harness';
    delete flags.harnessOnly;
  }
  if (flags.mode && !['harness', 'full'].includes(flags.mode)) {
    errors.push('--mode accepts: harness | full');
  }
  if (flags.agentFiles && !['add', 'replace'].includes(flags.agentFiles)) {
    errors.push('--agent-files accepts: add (only what is missing) | replace (replaces with a backup)');
  }
  if (flags.port != null) {
    const p = Number(flags.port);
    if (!Number.isInteger(p) || p < 1 || p > 65535) {
      errors.push('--port accepts a port number between 1 and 65535.');
    }
  }

  // `completo` predates the english-first rename and was always identical to
  // `saas` — accept it as a deprecated alias so old commands keep working.
  if (flags.preset === 'completo') {
    warnings.push("--preset completo is deprecated — it is the same as 'saas' (using saas).");
    flags.preset = 'saas';
  }
  if (flags.preset && !['minimo', 'padrao', 'saas'].includes(flags.preset)) {
    errors.push('--preset accepts: minimo | padrao | saas (completo is a deprecated alias of saas)');
  }
  if (flags.analytics && !['none', 'posthog', 'vercel-analytics'].includes(flags.analytics)) {
    errors.push('--analytics accepts: none | posthog | vercel-analytics');
  }
  if (flags.emails && !['none', 'resend'].includes(flags.emails)) {
    errors.push('--emails accepts: none | resend');
  }
  if (flags.payments && !['none', 'stripe', 'asaas', 'clerk-billing'].includes(flags.payments)) {
    errors.push('--payments accepts: none | stripe | asaas | clerk-billing');
  }
  if (flags.storage && !['convex', 'r2'].includes(flags.storage)) {
    errors.push('--storage accepts: convex | r2');
  }
  if (flags.tenancy && !['single', 'multi'].includes(flags.tenancy)) {
    errors.push('--tenancy accepts: single | multi');
  }

  // Modifier flags of the early-exit commands: outside them they do nothing —
  // say so instead of silently ignoring (almost always a typo'd invocation).
  if (flags.json && !flags.verify && !flags.updateRuntime) {
    warnings.push('--json only applies to --verify / --update-runtime — ignored.');
  }
  if (flags.force && !flags.updateRuntime) {
    warnings.push('--force only applies to --update-runtime — ignored.');
  }

  return { flags, errors, warnings };
}

function splitInline(token) {
  if (!token.startsWith('--')) return [token, null];
  const eq = token.indexOf('=');
  if (eq === -1) return [token, null];
  return [token.slice(0, eq), token.slice(eq + 1)];
}

export function helpText() {
  return `
impactus — IAI installer v2 (harness + FIA + Next.js + Convex + Clerk starters)

Run it with NO arguments and the assistant asks ALL the decisions right here
in the terminal (template, stack, shadcn, storage, GitHub, deploy…), shows a
summary for you to review, then runs everything at once. Any flag already
decided is no longer asked; with --yes nothing is asked.

The harness (agent workflow) is ALWAYS installed. The Next.js + Convex +
Clerk template is optional: pick the mode right at the start or pass --mode/--harness-only.

Usage:
  npx impactus                   # terminal assistant (recommended)
  npx impactus [name] [options]  # same, with decisions pre-answered via flags
  npx impactus --ui              # optional: build the command on a local page

Options:
  --dir <path>             Target folder ("." for the current folder). The
                           project NAME is that folder's name.
  --name <name>            Overrides the project name (same as the 1st
                           argument; without --dir, creates the ./<slug> subfolder)
  --mode <value>           harness (harness only) | full (harness + template)
  --harness-only           Shortcut for --mode harness (doesn't install the template)
  --stack <value>          recomendada (Next.js + Convex + Clerk + R2 template) |
                           propria (build it layer by layer in the assistant) |
                           depois (harness only; the stack stays pending and you
                           decide talking with Pi) | category=option pairs,
                           e.g.: backend=hono,db=neon,orm=drizzle,auth=clerk
                           (categories: frontend, backend, database, orm, auth,
                           blob, deploy — anything missing becomes "decide later")
  --agent-files <mode>     Project with agent files (.claude, CLAUDE.md…): add (default, only what's missing) | replace (backup + replace)
  --template-id <id>       Catalog template: live1 (default) | live2
  --template-ref <branch>  Template branch/tag on the gated download (test
                           branches as a student)

  --update-deps <mode>     Update dependencies after the download:
                           none (keep) | safe (npm update — patch/minor)
  --shadcn-preset <val>    shadcn/create preset (code or full command)
  --shadcn-block <blocks>  shadcn block(s) separated by commas, or "none"
  --skip-shadcn            Skips shadcn/ui customization

  Addons (whatever isn't chosen is REMOVED from the generated project):
  --preset <name>          minimo | padrao | saas
  --addons <list>          Quality/DX: commitlint,knip,analyzer
                           (or "none" / "all")
  --observability <list>   sentry,logging (or "none")
  --analytics <value>      none | posthog | vercel-analytics
  --security <list>        csp,rate-limit (or "none")
  --emails <value>         none | resend
  --platform <list>        notifications (or "none" / "all")
  --payments <value>       none | stripe | asaas | clerk-billing
  --tenancy <value>        single (Live 1, default) | multi (Live 2: your app's
                           own organizations in Convex — per-organization data/billing,
                           per-member roles and permissions, /admin with org management)

  --keys <file>            .env file with service keys (Stripe, Asaas,
                           Resend…) — the web UI (--ui) generates one in ~/.create-iai/keys/.
                           The keys stay on your machine only; the installer
                           applies them to Convex/.env.local and creates the webhooks via API.

  --skip-webhook           Skips the Clerk → Convex webhook
  --storage <value>        convex | r2 (file storage)
  --skip-storage           Skips the storage choice (uses Convex Storage)

  --repo <name>            GitHub repository name (default: project slug)
  --public | --private     Repository visibility (default: private)
  --push | --no-push       Create the repo on GitHub and push (or not)
  --skip-github            Skips commit + GitHub

  --deploy | --no-deploy   Deploy to Vercel at the end (or not)
  --skip-deploy            Same as --no-deploy

  --no-harness             (only with --mode full) installs the template WITHOUT the harness
  --skip-harness           Same as --no-harness

  --fia                    Installs FIA (Pi + FDAs + orchestrator skill)
  --no-fia                 Skips FIA in this installation
  --skip-fia               Same as --no-fia

  --impeccable             Installs the Impeccable design skill (impeccable.style)
                           in the project — free, open-source, no API key.
                           /impeccable commands (craft, audit, polish…) in Claude
                           Code, Cursor and Pi. Requires Node >= 22.12 (otherwise skipped).
  --no-impeccable          Skips the Impeccable skill in this installation
  --skip-impeccable        Same as --no-impeccable

  --ui, --web              Opens the local web UI to build the command by clicking
                           (optional — the terminal assistant is the default)
  --terminal, --no-ui      Accepted for compatibility (the terminal is already the default)
  --port <n>               UI server port (default: 4599)

  Access (the CLI is exclusive to community students with an active subscription):
  --login                  Authenticates this computer (opens the browser) and exits
  --logout                 Removes/revokes this computer's CLI token and exits
  --whoami                 Shows your subscription status and exits
  --api <url>              Community API base (dev/testing; or CREATE_IAI_API)

  --verify                 Audits an ALREADY-installed project (--dir points to the folder):
                           orphan markers, missing envs, leftover manifest…
  --update-runtime         Updates the FIA/Pi RUNTIME of an ALREADY-installed
                           project (--dir) to this impactus version: imp/ modules,
                           FDAs, scripts + the .pi/ fia skill, prompts and
                           extensions. imp/fia.config.yaml, imp/data/ and files
                           you edited are preserved (confirm or --force; every
                           overwrite is backed up to imp/.runtime-backup-<ts>/).
                           Projects from older versions (fia/ layout) are
                           migrated to imp/ automatically.
  --force                  With --update-runtime: overwrite locally modified
                           runtime files too (after backing them up)
  --json                   With --verify / --update-runtime: print the report as
                           JSON on stdout (scripts/CI)

  -y, --yes                Don't ask; use safe defaults for everything (full mode)
  -v, --version            Shows the version
  -h, --help               Shows this help

Examples:
  npx impactus my-app
  npx impactus --ui                            # build the install in the browser
  npx impactus my-app --harness-only           # harness only, in this folder
  npx impactus --dir . --harness-only --yes
  npx impactus my-app --yes --shadcn-block sidebar-07 --push --private
  npx impactus --dir . --update-deps safe --deploy
`.trimStart();
}
