import { test } from 'node:test';
import assert from 'node:assert/strict';
import { mkdtempSync, writeFileSync, mkdirSync, readFileSync, existsSync, rmSync, utimesSync } from 'node:fs';
import { join } from 'node:path';
import { tmpdir } from 'node:os';
import { execFileSync } from 'node:child_process';
import { snapshot, changedPaths, enforce, PermissionBreach } from '../fia-templates/modules/permissions.mjs';

function initGitRepo(root) {
  execFileSync('git', ['init'], { cwd: root, stdio: 'ignore' });
  execFileSync('git', ['config', 'user.email', 'fia@test.dev'], { cwd: root, stdio: 'ignore' });
  execFileSync('git', ['config', 'user.name', 'FIA Test'], { cwd: root, stdio: 'ignore' });
  // Windows runners default autocrlf=true globally — a revert would restore
  // CRLF bytes and break the literal content comparisons below.
  execFileSync('git', ['config', 'core.autocrlf', 'false'], { cwd: root, stdio: 'ignore' });
  writeFileSync(join(root, 'README.md'), '# test\n');
  execFileSync('git', ['add', 'README.md'], { cwd: root, stdio: 'ignore' });
  execFileSync('git', ['commit', '-m', 'init'], { cwd: root, stdio: 'ignore' });
}

test('changedPaths: detects new untracked file', () => {
  const before = { 'README.md': '1,1' };
  const after = { 'README.md': '1,1', 'new.txt': 'untracked' };
  assert.deepEqual(changedPaths(before, after), ['new.txt']);
});

test('enforce: scout with writes:[] cannot modify tracked files', () => {
  const root = mkdtempSync(join(tmpdir(), 'fia-perm-'));
  initGitRepo(root);
  const run = {
    repoRoot: root,
    cfg: { defaults: { protected_files: ['imp/modules/'] } },
  };
  const before = snapshot(run);
  writeFileSync(join(root, 'scout-note.txt'), 'read-only scout should not write\n');
  assert.throws(
    () =>
      enforce(run, {}, { name: 'scout', writes: [] }, before),
    PermissionBreach,
  );
  // Rollback: the unauthorized untracked file was removed.
  assert.equal(existsSync(join(root, 'scout-note.txt')), false);
});

test('enforce: builder without writes list may touch non-protected paths', () => {
  const root = mkdtempSync(join(tmpdir(), 'fia-perm-'));
  initGitRepo(root);
  mkdirSync(join(root, 'src'), { recursive: true });
  const run = {
    repoRoot: root,
    cfg: { defaults: { protected_files: ['imp/modules/'] } },
  };
  const before = snapshot(run);
  writeFileSync(join(root, 'src', 'app.js'), 'export {}\n');
  const touched = enforce(run, {}, { name: 'builder', writes: null }, before);
  assert.ok(touched.some((p) => p.endsWith('src/app.js')));
});

test('enforce: benign build artifacts are reverted without breach (Next.js AGENTS.md)', () => {
  const root = mkdtempSync(join(tmpdir(), 'fia-perm-'));
  initGitRepo(root);
  writeFileSync(join(root, 'AGENTS.md'), '# original guide\n');
  execFileSync('git', ['add', 'AGENTS.md'], { cwd: root, stdio: 'ignore' });
  execFileSync('git', ['commit', '-m', 'agents'], { cwd: root, stdio: 'ignore' });
  const events = [];
  const run = {
    repoRoot: root,
    fdaId: 't1',
    cfg: { defaults: { protected_files: ['imp/modules/'] } },
    tracer: { event: (e) => events.push(e) },
    console: { note: () => {} },
  };
  const before = snapshot(run);
  // Simulates `next build` rewriting AGENTS.md during a read-only review phase.
  writeFileSync(join(root, 'AGENTS.md'), '# generated by next\n');
  const touched = enforce(run, { phase_id: 'p1' }, { name: 'reviewer', writes: [] }, before);
  assert.ok(touched.some((p) => p.endsWith('AGENTS.md')));
  // Reverted to the committed content, logged as external_change, no throw.
  assert.equal(readFileSync(join(root, 'AGENTS.md'), 'utf8'), '# original guide\n');
  assert.ok(events.some((e) => e.name === 'external_change'));
});

test('enforce: project benign_paths extend the built-in list', () => {
  const root = mkdtempSync(join(tmpdir(), 'fia-perm-'));
  initGitRepo(root);
  const run = {
    repoRoot: root,
    fdaId: 't2',
    cfg: { defaults: { protected_files: [], permissions: { benign_paths: ['generated/'] } } },
    tracer: { event: () => {} },
    console: { note: () => {} },
  };
  const before = snapshot(run);
  mkdirSync(join(root, 'generated'), { recursive: true });
  writeFileSync(join(root, 'generated', 'types.d.ts'), 'export {}\n');
  writeFileSync(join(root, 'nota.txt'), 'outside the allowlist and not benign\n');
  assert.throws(
    () => enforce(run, { phase_id: 'p1' }, { name: 'scout', writes: [] }, before),
    (err) => err instanceof PermissionBreach && /nota\.txt/.test(err.message) && !/generated/.test(err.message),
  );
  // The benign path was cleaned up silently; the breach names only nota.txt.
  assert.equal(existsSync(join(root, 'generated', 'types.d.ts')), false);
});

test('enforce: modifying a pre-existing untracked file is detected and kept on disk', () => {
  const root = mkdtempSync(join(tmpdir(), 'fia-perm-'));
  initGitRepo(root);
  // .env.local exists BEFORE the phase and was never committed — the old
  // constant 'untracked' fingerprint made edits to it invisible.
  writeFileSync(join(root, '.env.local'), 'SECRET=original\n');
  const run = {
    repoRoot: root,
    cfg: { defaults: { protected_files: [] } },
  };
  const before = snapshot(run);
  writeFileSync(join(root, '.env.local'), 'SECRET=rewritten-by-the-agent-much-longer\n');
  assert.throws(
    () => enforce(run, {}, { name: 'scout', writes: [] }, before),
    (err) => err instanceof PermissionBreach && /\.env\.local/.test(err.message) && /NOT restorable/.test(err.message),
  );
  // No copy exists in git: the file must NOT be deleted (that would destroy
  // the user's only copy) — it is reported instead.
  assert.equal(existsSync(join(root, '.env.local')), true);
});

test('enforce: same-size edit to a pre-existing untracked file is detected', () => {
  const root = mkdtempSync(join(tmpdir(), 'fia-perm-'));
  initGitRepo(root);
  // Same byte length before and after — a stat (mtime+size) fingerprint could
  // miss this within one timestamp tick; the content hash never does.
  writeFileSync(join(root, '.env.local'), 'SECRET=aaaaaaaa\n');
  const run = {
    repoRoot: root,
    cfg: { defaults: { protected_files: [] } },
  };
  const before = snapshot(run);
  writeFileSync(join(root, '.env.local'), 'SECRET=bbbbbbbb\n');
  assert.throws(
    () => enforce(run, {}, { name: 'scout', writes: [] }, before),
    (err) => err instanceof PermissionBreach && /\.env\.local/.test(err.message) && /NOT restorable/.test(err.message),
  );
  // Never delete the user's only copy.
  assert.equal(existsSync(join(root, '.env.local')), true);
});

test('enforce: touching an untracked file without changing content is NOT a violation', () => {
  const root = mkdtempSync(join(tmpdir(), 'fia-perm-'));
  initGitRepo(root);
  writeFileSync(join(root, '.env.local'), 'SECRET=original\n');
  const run = {
    repoRoot: root,
    cfg: { defaults: { protected_files: [] } },
  };
  const before = snapshot(run);
  // Bump mtime only — identical content must not read as an "irrecoverable" breach.
  const later = new Date(Date.now() + 60_000);
  utimesSync(join(root, '.env.local'), later, later);
  const touched = enforce(run, {}, { name: 'scout', writes: [] }, before);
  assert.deepEqual(touched, []);
  assert.equal(readFileSync(join(root, '.env.local'), 'utf8'), 'SECRET=original\n');
});

test('enforce: deleting a pre-existing untracked file is an unrecoverable breach', () => {
  const root = mkdtempSync(join(tmpdir(), 'fia-perm-'));
  initGitRepo(root);
  writeFileSync(join(root, '.env.local'), 'SECRET=original\n');
  const run = {
    repoRoot: root,
    cfg: { defaults: { protected_files: [] } },
  };
  const before = snapshot(run);
  rmSync(join(root, '.env.local'));
  assert.throws(
    () => enforce(run, {}, { name: 'scout', writes: [] }, before),
    (err) =>
      err instanceof PermissionBreach &&
      /rolled back: 0\/1/.test(err.message) &&
      /deleted — the original content was never in git/.test(err.message),
  );
});

test('enforce: directory allowlist does not match sibling files sharing the prefix', () => {
  const root = mkdtempSync(join(tmpdir(), 'fia-perm-'));
  initGitRepo(root);
  const run = {
    repoRoot: root,
    cfg: { defaults: { protected_files: [] } },
  };
  const before = snapshot(run);
  mkdirSync(join(root, 'specs'), { recursive: true });
  writeFileSync(join(root, 'specs', 'ok.md'), '# inside the allowed directory\n');
  writeFileSync(join(root, 'specs-fake.md'), 'outside: "specs/" must not match "specs-fake.md"\n');
  assert.throws(
    () => enforce(run, {}, { name: 'planner', writes: ['specs/'] }, before),
    (err) => err instanceof PermissionBreach && /specs-fake\.md/.test(err.message) && !/specs\/ok\.md/.test(err.message),
  );
  // Allowed work preserved; the violating sibling was rolled back.
  assert.equal(existsSync(join(root, 'specs', 'ok.md')), true);
  assert.equal(existsSync(join(root, 'specs-fake.md')), false);
});

test('enforce: glob dot is literal — "docs/*.md" does not match "docs/notes_md"', () => {
  const root = mkdtempSync(join(tmpdir(), 'fia-perm-'));
  initGitRepo(root);
  const run = {
    repoRoot: root,
    cfg: { defaults: { protected_files: [] } },
  };
  const before = snapshot(run);
  mkdirSync(join(root, 'docs'), { recursive: true });
  writeFileSync(join(root, 'docs', 'notes_md'), 'the "." in the pattern must not match any character\n');
  assert.throws(
    () => enforce(run, {}, { name: 'documenter', writes: ['docs/*.md'] }, before),
    PermissionBreach,
  );
});

test('enforce: protected imp/ paths always blocked', () => {
  const root = mkdtempSync(join(tmpdir(), 'fia-perm-'));
  initGitRepo(root);
  mkdirSync(join(root, 'imp', 'modules'), { recursive: true });
  writeFileSync(join(root, 'imp', 'modules', 'runner.mjs'), '// protected\n');
  execFileSync('git', ['add', 'imp'], { cwd: root, stdio: 'ignore' });
  execFileSync('git', ['commit', '-m', 'add imp'], { cwd: root, stdio: 'ignore' });
  const run = {
    repoRoot: root,
    cfg: { defaults: { protected_files: ['imp/modules/'] } },
  };
  const before = snapshot(run);
  writeFileSync(join(root, 'imp', 'modules', 'runner.mjs'), '// tampered\n');
  assert.throws(
    () => enforce(run, {}, { name: 'builder', writes: ['**/*'] }, before),
    PermissionBreach,
  );
  // Rollback: the protected file was restored from HEAD.
  assert.equal(readFileSync(join(root, 'imp', 'modules', 'runner.mjs'), 'utf8'), '// protected\n');
});
