// Commands follow the same "one canonical + generated distribution" model as skills:
//   harness/.claude/commands/     — the ONLY side humans/agents edit
//   scripts/command-overlays.yaml — Cursor frontmatter + patchlets
//   harness/.cursor/commands/     — GENERATED by npm run sync:commands
//   harness/.agents/commands/     — symlinks at the Cursor copy (what Cursor opens)
import { test } from 'node:test';
import assert from 'node:assert/strict';
import { existsSync, readdirSync, readFileSync } from 'node:fs';
import { join, basename } from 'node:path';
import { fileURLToPath } from 'node:url';
import { spawnSync } from 'node:child_process';
import { parse as parseYaml } from 'yaml';

const ROOT = fileURLToPath(new URL('..', import.meta.url));
const HARNESS = join(ROOT, 'harness');
const SRC = join(HARNESS, '.claude', 'commands');
const DST = join(HARNESS, '.cursor', 'commands');
const OVERLAYS = join(ROOT, 'scripts', 'command-overlays.yaml');
const SYNC = join(ROOT, 'scripts', 'sync-commands.mjs');
const hasHarness = existsSync(SRC);
const skip = !hasHarness && 'harness/ not present (nested repo, absent on fresh checkout)';

const HARNESS_AGENTS = new Set([
  'api-docs-researcher',
  'component-architect',
  'screen-routes-generator',
  'start-mapper',
  'start-scaffolding',
  'task-master-generator',
  'task-sequencer',
  'ui-component-page',
  'ui-component-researcher',
]);

test('command-overlays.yaml covers every .claude command', { skip }, () => {
  const names = readdirSync(SRC)
    .filter((f) => f.endsWith('.md'))
    .map((f) => basename(f, '.md'))
    .sort();
  const overlays = parseYaml(readFileSync(OVERLAYS, 'utf8')).commands ?? {};
  const missing = names.filter((n) => !overlays[n]?.description);
  const stale = Object.keys(overlays).filter((n) => !names.includes(n));
  assert.deepEqual(missing, [], `missing overlay descriptions: ${missing.join(', ')}`);
  assert.deepEqual(stale, [], `stale overlay keys: ${stale.join(', ')}`);
});

test('sync:commands --check passes (cursor twins match generator)', { skip }, () => {
  const result = spawnSync(process.execPath, [SYNC, '--check'], { encoding: 'utf8' });
  assert.equal(result.status, 0, result.stdout + result.stderr);
  assert.match(result.stdout, /in sync/);
});

test('every .cursor command has frontmatter name matching filename', { skip }, () => {
  const problems = [];
  for (const file of readdirSync(DST).filter((f) => f.endsWith('.md')).sort()) {
    const expected = file.replace(/\.md$/, '');
    const text = readFileSync(join(DST, file), 'utf8');
    const m = text.match(/^---\r?\n[\s\S]*?^name:\s*(\S+)\s*$/m);
    if (!m) problems.push(`${file}: no frontmatter name:`);
    else if (m[1] !== expected) problems.push(`${file}: frontmatter name "${m[1]}" != "${expected}"`);
  }
  assert.deepEqual(problems, [], problems.join('\n'));
});

test('Cursor overlays preserve the one-copy project skill topology', { skip }, () => {
  const absorb = readFileSync(join(DST, 'absorb.md'), 'utf8');
  assert.match(absorb, /For Claude, create `.claude\/skills\/project`/);
  assert.match(absorb, /target is exactly `\.\.\/\.\.\/\.agents\/skills\/project`/);
  assert.match(absorb, /Never create `\.pi\/skills\/project` or `.cursor\/skills\/project` copies/);
  assert.doesNotMatch(absorb, /For Claude, create `.cursor\/skills\/project`/);
  for (const legacy of ['.claude/skills/project', '.cursor/skills/project', '.pi/skills/project']) {
    assert.match(absorb, new RegExp(legacy.replace(/[./]/g, '\\$&')));
  }

  for (const file of [join(SRC, 'stack.md'), join(DST, 'stack.md')]) {
    const stack = readFileSync(file, 'utf8');
    assert.doesNotMatch(stack, /-a pi\b/);
    assert.match(stack, /single canonical project skill/);
    assert.match(stack, /Create `\.claude\/skills\/<tech>` as a directory symlink to/);
    assert.doesNotMatch(stack, /Create `\.cursor\/skills\/<tech>` as a directory symlink to/);
    assert.match(stack, /Never create `.cursor\/skills\/<tech>` or\s+`\.pi\/skills\/<tech>` copies/);
    for (const location of [
      '.agents/skills/<tech>',
      '.claude/skills/<tech>',
      '.cursor/skills/<tech>',
      '.pi/skills/<tech>',
    ]) {
      assert.match(stack, new RegExp(location.replace(/[./]/g, '\\$&')));
    }
    assert.match(stack, /including each symlink target/);
    assert.match(stack, /preserve every version/);
    assert.match(stack, /which version is authoritative/);
    assert.match(stack, /Never\s+overwrite, delete, or silently merge a legacy skill/);
  }
  const piStack = readFileSync(join(ROOT, 'pi-templates', '.pi', 'skills', 'fia', 'cookbooks', 'stack.md'), 'utf8');
  assert.doesNotMatch(piStack, /-a pi\b/);
  assert.match(piStack, /single canonical project skill/);
  assert.match(piStack, /Never create `.cursor\/skills\/<tech>` or\s+`\.pi\/skills\/<tech>` copies/);
  for (const location of [
    '.agents/skills/<tech>',
    '.claude/skills/<tech>',
    '.cursor/skills/<tech>',
    '.pi/skills/<tech>',
  ]) {
    assert.match(piStack, new RegExp(location.replace(/[./]/g, '\\$&')));
  }
  assert.match(piStack, /including each symlink target/);
  assert.match(piStack, /preserve every version/);
  assert.match(piStack, /which version is authoritative/);
  assert.match(piStack, /Never\s+overwrite, delete, or silently merge a legacy skill/);
});

test('harness-backed Pi agents point at .claude/agents/ instead of restating the prompt', { skip }, () => {
  const piAgents = join(ROOT, 'pi-templates', '.pi', 'agents');
  const problems = [];
  for (const name of HARNESS_AGENTS) {
    const file = join(piAgents, `${name}.md`);
    assert.ok(existsSync(file), `${name}.md missing from pi-templates`);
    const text = readFileSync(file, 'utf8');
    const body = text.replace(/^---[\s\S]*?---\r?\n?/, '');
    const lines = body.split('\n').filter((l) => l.trim()).length;
    assert.ok(lines <= 8, `${name}: Pi wrapper grew to ${lines} body lines — restating the harness agent?`);
    if (!text.includes('`.claude/agents/' + name + '.md`')) {
      problems.push(`${name}: missing pointer to .claude/agents/${name}.md`);
    }
    if (text.includes('You are the harness') && text.includes('adapted for the FIA roster')) {
      problems.push(`${name}: still restates the old one-paragraph harness summary`);
    }
  }
  assert.deepEqual(problems, [], problems.join('\n'));
});

test('FIA-only Pi agents stay self-contained (no harness pointer required)', () => {
  const fiaOnly = ['planner', 'builder', 'scout', 'reviewer', 'documenter'];
  const piAgents = join(ROOT, 'pi-templates', '.pi', 'agents');
  for (const name of fiaOnly) {
    const text = readFileSync(join(piAgents, `${name}.md`), 'utf8');
    assert.doesNotMatch(text, /\.claude\/agents\//, `${name} should not point at a harness agent`);
    assert.ok(text.includes('FIA'), `${name} should identify as an FIA roster agent`);
  }
});
