// Step: activate the chosen integrations with the service keys.
//
// Keys arrive by two paths:
//   1. `--keys` file (generated by the web UI when pasting the keys in the
//      browser — stays on the machine only, permission 600);
//   2. pasted here in the terminal (with the option to see the SAME AI prompt
//      as the UI, for a browser extension to fetch the keys from the dashboard).
//
// Each env is written where the template actually reads it: the Convex
// deployment (`npx convex env set`, mirrored into .env.local for documentation)
// or only .env.local (Next.js NEXT_PUBLIC_* vars). Bonus: with the key in hand,
// the CLI creates the payment webhooks VIA API (Stripe and Asaas) pointing at
// the deployment — no manual dashboard step. Everything is optional and
// best-effort: without a key, the addon degrades gracefully (as always) and the
// final summary lists what's still pending.

import { join } from 'node:path';
import { readFile } from 'node:fs/promises';
import { ENV_FILE, EXTRA_SERVICE_KEYS, PAYMENT_WEBHOOKS } from '../config.js';
import { run } from '../lib/proc.js';
import { redactSecret } from '../lib/log.js';
import { upsertEnvVar } from '../lib/env-file.js';
import { generateToken } from '../lib/keys.js';
import {
  buildServicePrompt,
  dashboardEnvs,
  relevantServices,
  validateEnvValue,
} from '../lib/service-prompts.js';
import * as ui from '../lib/ui.js';

export async function setupServiceKeys(ctx) {
  const provided = { ...(ctx.providedKeys || {}) };
  ctx.serviceReport = ctx.serviceReport || [];

  // R2 is handled in the storage step (wrangler); here come the addon
  // services that need a dashboard key.
  const services = relevantServices({ addons: ctx.addons ?? [] }).filter((s) => s.setup === 'keys');
  if (services.length === 0) {
    ui.info('None of the chosen integrations needs keys right now.');
    return;
  }

  ui.note(
    [
      'Time to activate the chosen integrations. Every key is OPTIONAL — without',
      'it the feature stays dormant and you activate it later (the final summary',
      'shows how).',
      '',
      'Tip: every service has a ready-made AI prompt — paste it into a browser',
      'automation extension (e.g. Claude in Chrome) and it fetches the keys for',
      'you, returning them in the exact format I recognize.',
      '',
      '🔒 Keys pasted here stay on your machine only (.env.local and your Convex',
      'deployment) — never in the command nor in the shell history.',
    ].join('\n'),
    'Integrations — service keys',
  );

  for (const service of services) {
    await configureService(ctx, service, provided);
  }

  // Extras from the --keys file outside the field catalog (EMAIL_FROM etc.):
  // applied directly when the matching addon was chosen.
  for (const [key, spec] of Object.entries(EXTRA_SERVICE_KEYS)) {
    const value = provided[key];
    if (!value || !(ctx.addons ?? []).includes(spec.service)) continue;
    const ok = await applyEnv(ctx, { key, target: spec.target, secret: true }, String(value).trim());
    if (ok) {
      ctx.keysApplied = true;
      ui.success(`${key} applied (extra from the keys file).`);
    }
  }
}

/**
 * A dashboard env only "counts" when the user actually provided it — a value
 * equal to the factory default (e.g. NEXT_PUBLIC_POSTHOG_HOST) activates nothing.
 */
function hasRealDashboardValue(service, values) {
  return dashboardEnvs(service).some((e) => values[e.key] && values[e.key] !== e.default);
}

/** Collects and applies a service's envs; feeds ctx.serviceReport. */
async function configureService(ctx, service, provided) {
  const { flags = {} } = ctx;
  const values = {};

  // 1. What already arrived ready (the UI's --keys file) — validating the format.
  for (const spec of service.envs) {
    const raw = provided[spec.key];
    if (raw == null || raw === '') continue;
    const check = validateEnvValue(spec, raw);
    if (check === true) values[spec.key] = String(raw).trim();
    else ui.warn(`${spec.key} from the keys file looks invalid (${check}) — ignoring.`);
  }

  // 2. Local sources: generated ones and automatic ones with a default.
  for (const spec of service.envs) {
    if (values[spec.key]) continue;
    if (spec.source === 'generate') values[spec.key] = generateToken();
    if (spec.source === 'auto' && spec.default) values[spec.key] = spec.default;
  }

  // 3. Interactive: what's missing from the dashboard/user. "Skip" stops
  //    asking about this service — no ASAAS_VALUE after the skip (whatever
  //    already came ready from the file is still applied normally).
  let skippedByUser = false;
  const missingDashboard = dashboardEnvs(service).filter((e) => !values[e.key]);
  if (!flags.yes && missingDashboard.length > 0) {
    skippedByUser = (await askForService(ctx, service, values, missingDashboard)) === 'skip';
  }
  if (!skippedByUser && !flags.yes && hasRealDashboardValue(service, values)) {
    for (const spec of service.envs.filter((e) => e.source === 'user' && !values[e.key])) {
      const answer = await ui.text({
        message: `${spec.key} — ${spec.label}:`,
        defaultValue: spec.default ?? '',
        placeholder: spec.default ?? spec.patternHint ?? '',
        validate: (v) => {
          const val = String(v ?? '').trim() || spec.default || '';
          if (!val) return undefined;
          const check = validateEnvValue(spec, val);
          return check === true ? undefined : check;
        },
      });
      const value = String(answer ?? '').trim() || spec.default || '';
      if (value) values[spec.key] = value;
    }
  }
  for (const spec of service.envs.filter((e) => e.source === 'user' && !values[e.key] && e.default)) {
    values[spec.key] = spec.default;
  }

  const gotDashboard = hasRealDashboardValue(service, values);
  if (!gotDashboard) {
    ctx.serviceReport.push({
      id: service.id,
      label: service.label,
      ok: false,
      detail: 'no keys — feature dormant until you activate it (instructions in the final summary)',
    });
    ui.info(`${service.label}: skipped for now.`);
    return;
  }

  // Dashboard keys with a default (e.g. the PostHog host): fill in the
  // default when the user only brought the others.
  for (const spec of dashboardEnvs(service).filter((e) => e.default && !values[e.key])) {
    values[spec.key] = spec.default;
  }

  // No secrets in the execution log (it's the file we ask for in bug reports).
  for (const spec of service.envs) {
    if (spec.secret && values[spec.key]) redactSecret(values[spec.key]);
  }

  // 4. Apply each value to the right destination.
  const applied = [];
  for (const spec of service.envs) {
    const value = values[spec.key];
    if (!value) continue;
    const ok = await applyEnv(ctx, spec, value);
    if (ok) {
      applied.push(spec.key);
      if (provided[spec.key]) ctx.keysApplied = true;
    }
  }

  // 5. Payment webhooks created via API (with a manual fallback in the summary).
  let webhookNote = null;
  if (service.id === 'stripe') webhookNote = await ensureStripeWebhook(ctx, values);
  if (service.id === 'asaas') webhookNote = await ensureAsaasWebhook(ctx, values);

  const pending = service.envs
    .filter((e) => e.source === 'dashboard' && !values[e.key])
    .map((e) => e.key);
  ctx.serviceReport.push({
    id: service.id,
    label: service.label,
    ok: pending.length === 0,
    detail:
      (pending.length ? `missing: ${pending.join(', ')}` : `active (${applied.join(', ')})`) +
      (webhookNote ? ` · ${webhookNote}` : ''),
  });
  ui.success(`${service.label}: ${applied.length} key(s) applied.`);
}

/**
 * Interactive flow for one service: show the AI prompt and/or paste keys.
 * @returns {'skip'|'done'} 'skip' when the user skipped the whole service.
 */
async function askForService(ctx, service, values, missing) {
  ui.note(
    [
      service.keyNote || `Dashboard keys: ${service.dashboardUrl}`,
      service.autoNote ? `\n${service.autoNote}` : null,
    ]
      .filter(Boolean)
      .join('\n'),
    service.label,
  );

  const how = await ui.select({
    message: `Set up ${service.label} now?`,
    initialValue: 'prompt',
    options: [
      {
        value: 'prompt',
        label: 'See the AI prompt and paste the keys',
        hint: 'the browser extension fetches the keys for you',
      },
      { value: 'paste', label: 'I already have the keys — paste now' },
      { value: 'skip', label: 'Skip — activate later', hint: 'the feature stays dormant, nothing breaks' },
    ],
  });
  if (how === 'skip') return 'skip';

  if (how === 'prompt') {
    const prompt = buildServicePrompt(service, ctx.name);
    if (prompt) {
      ui.note(prompt, `Copy and paste into the browser AI extension — ${service.label}`);
      ui.info('When the agent returns the keys, paste each value below.');
    }
  }

  for (const spec of missing) {
    const message = `${spec.key} — ${spec.label} (empty to skip):`;
    const validate = (v) => {
      const val = String(v ?? '').trim();
      if (!val) return undefined;
      const check = validateEnvValue(spec, val);
      return check === true ? undefined : check;
    };
    const answer = spec.secret
      ? await ui.password({ message, validate })
      : await ui.text({ message, placeholder: spec.patternHint ?? '', validate });
    const value = String(answer ?? '').trim();
    if (value) values[spec.key] = value;
  }
  return 'done';
}

/** Writes an env to the right destination. Convex → deployment + mirror in .env.local. */
async function applyEnv(ctx, spec, value) {
  const envLocal = join(ctx.dir, ENV_FILE);
  if (spec.target === 'convex') {
    const r = await run('npx', ['convex', 'env', 'set', spec.key, value], { cwd: ctx.dir });
    if (!r.ok) {
      ui.warn(`I couldn't set ${spec.key} in Convex. Run later:\n  npx convex env set ${spec.key} <value>`);
      return false;
    }
  }
  await upsertEnvVar(envLocal, spec.key, value);
  return true;
}

// ── Payment webhooks via API ─────────────────────────────────────────────────

function convexSiteUrl(ctx) {
  return ctx.convexUrl ? ctx.convexUrl.replace('.convex.cloud', '.convex.site') : null;
}

/**
 * Discovers the API version pinned by the stripe-node INSTALLED in the project
 * (node_modules/stripe/esm/apiVersion.js) — the webhook endpoint must be
 * created on that same version so the payload has the shape the code reads.
 */
async function projectStripeApiVersion(dir) {
  for (const rel of ['esm/apiVersion.js', 'lib/apiVersion.js']) {
    try {
      const text = await readFile(join(dir, 'node_modules', 'stripe', rel), 'utf8');
      const m = /ApiVersion\s*=\s*['"]([^'"]+)['"]/.exec(text);
      if (m) return m[1];
    } catch {
      /* try the next path */
    }
  }
  return null;
}

/**
 * Creates the webhook endpoint in Stripe (test mode) and stores the signing secret.
 * @returns {Promise<string|null>} short note for the report.
 */
async function ensureStripeWebhook(ctx, values) {
  const sk = values.STRIPE_SECRET_KEY;
  const site = convexSiteUrl(ctx);
  if (!sk || !site) return null;
  if (values.STRIPE_WEBHOOK_SECRET) return 'webhook already provided';

  const url = `${site}${PAYMENT_WEBHOOKS.stripe.route}`;
  const body = new URLSearchParams({ url, description: 'create-iai (dev)' });
  for (const ev of PAYMENT_WEBHOOKS.stripe.events) body.append('enabled_events[]', ev);
  const apiVersion = await projectStripeApiVersion(ctx.dir);
  if (apiVersion) body.append('api_version', apiVersion);

  try {
    const res = await fetch('https://api.stripe.com/v1/webhook_endpoints', {
      method: 'POST',
      headers: { Authorization: `Bearer ${sk}`, 'Content-Type': 'application/x-www-form-urlencoded' },
      body,
    });
    const data = await res.json().catch(() => ({}));
    if (res.ok && data.secret) {
      redactSecret(data.secret);
      const okSet = await applyEnv(ctx, { key: 'STRIPE_WEBHOOK_SECRET', target: 'convex' }, data.secret);
      if (okSet) {
        ui.success(`Stripe webhook created via API → ${url}`);
        return 'webhook created via API';
      }
    }
    ui.warn(`I couldn't create the Stripe webhook via API (${data?.error?.message || res.status}).`);
  } catch (e) {
    ui.warn(`Failed to call the Stripe API: ${String(e)}`);
  }
  ui.note(stripeWebhookHowTo(url), 'Stripe — create the webhook manually');
  return 'webhook pending (manual)';
}

function stripeWebhookHowTo(url) {
  return [
    '1) dashboard.stripe.com (Test mode) → Developers → Webhooks → Add endpoint',
    `2) URL: ${url}`,
    `3) Events: ${PAYMENT_WEBHOOKS.stripe.events.join(', ')}`,
    '4) Copy the Signing secret and run in the project folder:',
    '   npx convex env set STRIPE_WEBHOOK_SECRET whsec_...',
  ].join('\n');
}

/**
 * Creates the Asaas webhook (v3) authenticated by the API key itself, using
 * the same authToken the backend validates in the `asaas-access-token` header.
 * The API requires an `email` for failure notices — we try the account's own
 * (GET /myAccount) and, in interactive mode, ask as a fallback.
 */
async function ensureAsaasWebhook(ctx, values) {
  const apiKey = values.ASAAS_API_KEY;
  const site = convexSiteUrl(ctx);
  if (!apiKey || !site) return null;

  const base =
    values.ASAAS_ENV === 'production' ? 'https://api.asaas.com/v3' : 'https://api-sandbox.asaas.com/v3';
  const url = `${site}${PAYMENT_WEBHOOKS.asaas.route}`;

  let email = null;
  try {
    const acc = await fetch(`${base}/myAccount`, { headers: { access_token: apiKey } });
    if (acc.ok) {
      const info = await acc.json().catch(() => ({}));
      email = info.email || info.loginEmail || null;
    }
  } catch {
    /* continue to the fallback */
  }
  if (!email && !ctx.flags?.yes) {
    const answer = await ui.text({
      message: 'E-mail for Asaas to report webhook failures (empty to skip the automatic creation):',
      placeholder: 'you@example.com',
    });
    email = String(answer ?? '').trim() || null;
  }
  if (!email) {
    ui.note(asaasWebhookHowTo(url, values.ASAAS_WEBHOOK_TOKEN), 'Asaas — create the webhook manually');
    return 'webhook pending (manual)';
  }

  try {
    const res = await fetch(`${base}/webhooks`, {
      method: 'POST',
      headers: { access_token: apiKey, 'Content-Type': 'application/json' },
      body: JSON.stringify({
        name: 'create-iai',
        url,
        email,
        enabled: true,
        interrupted: false,
        apiVersion: 3,
        sendType: 'SEQUENTIALLY',
        authToken: values.ASAAS_WEBHOOK_TOKEN,
        events: PAYMENT_WEBHOOKS.asaas.events,
      }),
    });
    if (res.ok) {
      ui.success(`Asaas webhook created via API → ${url}`);
      return 'webhook created via API';
    }
    const txt = await res.text();
    if (/already|existe|duplicad/i.test(txt)) {
      ui.info('The Asaas webhook already existed — kept.');
      return 'webhook already existed';
    }
    ui.warn(`I couldn't create the Asaas webhook via API (${res.status}): ${txt.slice(0, 160)}`);
  } catch (e) {
    ui.warn(`Failed to call the Asaas API: ${String(e)}`);
  }
  ui.note(asaasWebhookHowTo(url, values.ASAAS_WEBHOOK_TOKEN), 'Asaas — create the webhook manually');
  return 'webhook pending (manual)';
}

function asaasWebhookHowTo(url, token) {
  return [
    '1) Asaas dashboard → Minha Conta → Integrações → Webhooks → Criar',
    `2) URL: ${url}`,
    `3) Authentication token: ${token || '(the ASAAS_WEBHOOK_TOKEN value in your .env.local)'}`,
    `4) Events: ${PAYMENT_WEBHOOKS.asaas.events.join(', ')}`,
  ].join('\n');
}
