// `npx impactus --verify [--dir folder]` — audit of an ALREADY installed
// project. Changes nothing: it only checks what the installation promised and
// lists EXACTLY what is out of place (verify pattern: fail loudly, point at
// the file).
// `--json` swaps the human report for `{ ok, errors, warnings }` on stdout
// (scripts/CI); the exit code is the same either way.
//
// Audited dimensions:
//   1. package.json valid and with a name set;
//   2. addons contract: iai.config.json present, template.addons.json
//      manifest ABSENT (pruning removes it) and NO orphan live1:addon:*
//      marker left in the tree (pruning removes them all);
//   3. envs: .env.local with the base keys (Convex + Clerk) and the keys of
//      the services for the chosen addons (missing = warning — everything
//      degrades gracefully on its own);
//   4. installation: node_modules and convex/_generated present;
//   5. agent skills: every skill in skills-lock.json actually present in
//      .agents/skills/<name>/ — the ONE canonical store (Cursor and Pi read
//      it directly; .claude/skills/ symlinks into it) — and, when the project
//      has a .pi/, NOT duplicated in .pi/skills/<name>/ (Pi dedupes by
//      realpath: a copy there means the "Skill conflicts" panel at every
//      launch). Warning-level: the project runs fine, one engine is just
//      blind to the skill (or Pi nags about the duplicate).

import { existsSync } from 'node:fs';
import { readdir, readFile, stat } from 'node:fs/promises';
import { join, resolve } from 'node:path';
import {
  ADDONS_CONFIG_FILE,
  ADDONS_MANIFEST_FILE,
  ENV_FILE,
  HARNESS,
  LEGACY_ADDONS_CONFIG_FILE,
  SERVICES,
} from '../config.js';
import { MARKER_HINT } from '../lib/addons.js';
import * as ui from '../lib/ui.js';

// Keys that EVERY full installation writes to .env.local.
const CORE_ENV_KEYS = [
  'NEXT_PUBLIC_CONVEX_URL',
  'NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY',
  'CLERK_SECRET_KEY',
];

// Lockfile the skills.sh CLI writes (and the project commits) — the list of
// which skills this project promised to ship to the agents.
const SKILLS_LOCK_FILE = 'skills-lock.json';

const SKIP_DIRS = new Set(['node_modules', '.git', '.next', '_generated', 'public']);
const TEXT_EXT = /\.(ts|tsx|js|jsx|mjs|mts|cjs|json|yml|yaml|md|css|example|txt)$/;

/**
 * Audits `dir` and returns the list of findings (pure except for disk reads —
 * unit-testable with a fixture folder).
 * @returns {Promise<{level: 'error'|'warn'|'ok', msg: string}[]>}
 */
export async function collectFindings(dir) {
  const findings = [];
  const ok = (msg) => findings.push({ level: 'ok', msg });
  const warn = (msg) => findings.push({ level: 'warn', msg });
  const error = (msg) => findings.push({ level: 'error', msg });

  // 0. Install type. "Harness only" installs never ran the template: no addon
  //    contract, no Convex/Clerk envs, possibly no package.json at all —
  //    auditing those would report false errors. Detected by the harness'
  //    footprint (imp/HARNESS.md — or the legacy root HARNESS.md — / ai-docs/)
  //    WITHOUT the template's addons config.
  //    A convex/ folder means the template (any CLI version) did run — keeps
  //    projects from older CLI versions (no addons config yet) fully audited.
  //    The addons config lives at imp/iai.config.json; projects from older
  //    versions still keep it at the root.
  const addonsConfigName = [ADDONS_CONFIG_FILE, LEGACY_ADDONS_CONFIG_FILE].find((p) =>
    existsSync(join(dir, p)),
  );
  const harnessOnly =
    !addonsConfigName &&
    !existsSync(join(dir, 'convex')) &&
    (existsSync(join(dir, HARNESS.readmeAs)) ||
      existsSync(join(dir, 'HARNESS.md')) ||
      existsSync(join(dir, 'ai-docs')));

  // 1. package.json
  let pkg = null;
  try {
    pkg = JSON.parse(await readFile(join(dir, 'package.json'), 'utf8'));
    ok(`package.json valid (${pkg.name || 'no name'})`);
    if (!pkg.name) warn('package.json has no "name" — the installer sets the project slug.');
  } catch {
    if (harnessOnly) {
      warn('package.json missing or invalid — fine for a harness-only install (installing FIA adds a minimal one).');
    } else {
      error(`package.json missing or invalid in ${dir} — is this a project generated by the CLI?`);
      return findings; // without package.json the rest makes no sense
    }
  }

  if (harnessOnly) {
    ok(`harness-only install detected (${HARNESS.readmeAs}/ai-docs without the template)`);
    ok('addons contract: skip (harness-only install)');
    ok(`${ENV_FILE} core keys: skip (harness-only install)`);
    ok('node_modules / convex/_generated: skip (harness-only install)');
    // The stack step installs official skills in this mode too — still audited.
    findings.push(...(await skillsFindings(dir)));
    return findings;
  }

  // 2. Addons contract.
  let chosen = null;
  const configName = addonsConfigName ?? ADDONS_CONFIG_FILE;
  try {
    const cfg = JSON.parse(await readFile(join(dir, configName), 'utf8'));
    chosen = Array.isArray(cfg.addons) ? cfg.addons : [];
    ok(`${configName}: ${chosen.length ? chosen.join(', ') : 'no addons'}`);
  } catch {
    warn(`${ADDONS_CONFIG_FILE} not found — project from an older CLI version? (addon checks will be skipped)`);
  }

  if (existsSync(join(dir, ADDONS_MANIFEST_FILE))) {
    error(`${ADDONS_MANIFEST_FILE} still exists — addon pruning did not run (or it was restored by mistake). The installer removes this file.`);
  } else {
    ok(`${ADDONS_MANIFEST_FILE} absent (pruning executed)`);
  }

  const marked = await filesWithMarkers(dir);
  if (marked.length > 0) {
    error(
      `orphan "${MARKER_HINT}" markers in ${marked.length} file(s) — pruning removes them all. ` +
        `E.g.: ${marked.slice(0, 5).join(', ')}${marked.length > 5 ? ', …' : ''}`,
    );
  } else {
    ok('no orphan addon marker in the tree');
  }

  // 3. Envs
  const envPath = join(dir, ENV_FILE);
  if (!existsSync(envPath)) {
    error(`${ENV_FILE} does not exist — the installer always creates it.`);
  } else {
    const env = parseEnvFile(await readFile(envPath, 'utf8'));
    for (const key of CORE_ENV_KEYS) {
      if (env[key]) ok(`${key} set`);
      else error(`${key} empty/missing in ${ENV_FILE} — the app will not start without it.`);
    }
    if (chosen) {
      for (const svc of SERVICES) {
        if (!svc.when?.addon || !chosen.includes(svc.when.addon)) continue;
        const missing = svc.envs
          .filter((e) => e.source === 'dashboard' || e.source === 'user')
          .filter((e) => !env[e.key])
          .map((e) => e.key);
        if (missing.length === 0) {
          ok(`${svc.label}: keys present`);
        } else {
          warn(
            `${svc.label}: missing ${missing.join(', ')} — the addon degrades gracefully until configured ` +
              `(dashboard: ${svc.dashboardUrl || 'see README'}).`,
          );
        }
      }
    }
  }

  // 4. Installation
  if (existsSync(join(dir, 'node_modules'))) ok('node_modules present');
  else warn('node_modules missing — run `npm install`.');
  if (existsSync(join(dir, 'convex'))) {
    if (existsSync(join(dir, 'convex', '_generated'))) ok('convex/_generated present');
    else warn('convex/_generated missing — run `npx convex codegen` (or `npm run dev:convex`).');
  }

  // 5. Agent skills coverage.
  findings.push(...(await skillsFindings(dir)));

  return findings;
}

/**
 * Coverage of the skills recorded in skills-lock.json. `skills add` writes the
 * canonical copy to .agents/skills/<name>/ — read directly by Cursor AND by
 * Pi's native .agents/ discovery, symlinked into .claude/skills/ — so a lock
 * entry with no folder there means every engine is blind to the skill
 * (typical after a fresh clone, where only the lockfile is committed). A copy
 * in .pi/skills/ is the OPPOSITE problem: old installer versions made one per
 * skill, and Pi then loads everything twice and opens each session with a
 * "Skill conflicts" panel. Warning-level and self-contained so the
 * harness-only path can reuse it.
 * @returns {Promise<{level: 'warn'|'ok', msg: string}[]>}
 */
async function skillsFindings(dir) {
  const lockPath = join(dir, SKILLS_LOCK_FILE);
  if (!existsSync(lockPath)) return []; // no official skills in this project

  let names;
  try {
    const lock = JSON.parse(await readFile(lockPath, 'utf8'));
    names = Object.keys(lock?.skills || {});
  } catch {
    return [{ level: 'warn', msg: `${SKILLS_LOCK_FILE} is not valid JSON — the agent skills cannot be audited (or restored with \`npx skills experimental_install\`).` }];
  }
  if (names.length === 0) return [{ level: 'ok', msg: `${SKILLS_LOCK_FILE}: no skill recorded` }];

  const out = [];
  const missingStore = names.filter((n) => !existsSync(join(dir, '.agents', 'skills', n)));
  if (missingStore.length > 0) {
    out.push({
      level: 'warn',
      msg:
        `${missingStore.length} skill(s) in ${SKILLS_LOCK_FILE} missing from .agents/skills/ (${sample(missingStore)}) — Cursor reads that folder ` +
        '(and .claude/skills/ symlinks into it), so those skills are invisible. Restore with `npx skills experimental_install`.',
    });
  }

  // Leftover .pi/skills/ copies from the old install flow (only relevant when
  // the FIA was installed — and only for lock-recorded skills, never for the
  // harness-owned ones like .pi/skills/fia/).
  const hasPi = existsSync(join(dir, '.pi'));
  const stalePi = hasPi ? names.filter((n) => existsSync(join(dir, '.pi', 'skills', n))) : [];
  if (stalePi.length > 0) {
    out.push({
      level: 'warn',
      msg:
        `${stalePi.length} skill(s) duplicated in .pi/skills/ (${sample(stalePi)}) — Pi already reads .agents/skills/, so the copies only ` +
        'produce the "Skill conflicts" panel at every launch. Run `imp init --update-runtime` (or delete those folders) to clean them.',
    });
  }

  if (out.length === 0) {
    out.push({
      level: 'ok',
      msg: `${SKILLS_LOCK_FILE}: ${names.length} skill(s) available in .agents/skills/ (Cursor, Pi and the .claude/skills/ symlinks)`,
    });
  }
  return out;
}

/** First few names of a list, `…` when there are more (keeps messages short). */
function sample(names, max = 5) {
  return names.slice(0, max).join(', ') + (names.length > max ? ', …' : '');
}

/** Scan the tree for ANY leftover addon marker. */
async function filesWithMarkers(root) {
  const hits = [];
  async function walk(dirPath, relPath) {
    const entries = await readdir(dirPath, { withFileTypes: true });
    for (const entry of entries) {
      const full = join(dirPath, entry.name);
      const rel = relPath ? `${relPath}/${entry.name}` : entry.name;
      if (entry.isDirectory()) {
        if (!SKIP_DIRS.has(entry.name)) await walk(full, rel);
        continue;
      }
      if (!TEXT_EXT.test(entry.name) && entry.name !== '.env.example') continue;
      const info = await stat(full);
      if (info.size > 1024 * 1024) continue;
      const content = await readFile(full, 'utf8');
      if (content.includes(MARKER_HINT)) hits.push(rel);
    }
  }
  await walk(root, '');
  return hits;
}

/** Minimal .env parser (KEY=value, ignores comments and blank lines). */
export function parseEnvFile(content) {
  const out = {};
  for (const line of String(content).split('\n')) {
    const trimmed = line.trim();
    if (!trimmed || trimmed.startsWith('#')) continue;
    const eq = trimmed.indexOf('=');
    if (eq === -1) continue;
    const key = trimmed.slice(0, eq).trim();
    let value = trimmed.slice(eq + 1).trim();
    // Double-quoted values: also undo the internal escaping upsertEnvVar
    // applies (\" → "), so a value round-trips write → read unchanged.
    if (/^".*"$/.test(value)) value = value.slice(1, -1).replace(/\\"/g, '"');
    else value = value.replace(/^["']|["']$/g, '');
    if (key) out[key] = value;
  }
  return out;
}

/** Machine shape of `--verify --json` (pure — unit-testable on findings). */
export function jsonReport(findings) {
  return {
    ok: !findings.some((f) => f.level === 'error'),
    errors: findings.filter((f) => f.level === 'error').map((f) => f.msg),
    warnings: findings.filter((f) => f.level === 'warn').map((f) => f.msg),
  };
}

/** Entry point of `--verify`. @returns {Promise<boolean>} true = no errors. */
export async function runVerify(flags = {}) {
  const dir = resolve(String(flags.dir || '.'));

  // --json: machine-readable, stdout is ONLY the JSON (no clack chrome).
  if (flags.json) {
    const report = jsonReport(await collectFindings(dir));
    console.log(JSON.stringify(report, null, 2));
    return report.ok;
  }

  ui.intro('impactus --verify');
  ui.message(`Auditing the project at ${dir}…`);

  const findings = await collectFindings(dir);
  for (const f of findings) {
    if (f.level === 'ok') ui.success(f.msg);
    else if (f.level === 'warn') ui.warn(f.msg);
    else ui.error(f.msg);
  }

  const errors = findings.filter((f) => f.level === 'error').length;
  const warns = findings.filter((f) => f.level === 'warn').length;
  if (errors === 0) {
    ui.outro(
      warns === 0
        ? 'All good — project intact. ✅'
        : `Project intact, with ${warns} pending-configuration warning(s). ✅`,
    );
    return true;
  }
  ui.outro(ui.color.red(`${errors} problem(s) found (and ${warns} warning(s)). Fix the items above and run again.`));
  return false;
}
